name: Manual Version Bump

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type (patch, minor, major)'
        required: false
        default: 'patch'

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.10.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Bump version in package.json
        run: npm version ${{ github.event.inputs.bump || 'patch' }} --no-git-tag-version

      - name: Update version in manifest.ts
        id: update_manifest
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "New version: $VERSION"
          sed -i "s/version: *['\"][^'\"]*['\"]/version: '$VERSION'/" src/manifest.ts
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b bump-version-${{ steps.update_manifest.outputs.version }}
          git add package.json package-lock.json src/manifest.ts
          git commit -m "chore: bump version to ${{ steps.update_manifest.outputs.version }}"
          git push origin bump-version-${{ steps.update_manifest.outputs.version }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bump-version-${{ steps.update_manifest.outputs.version }}
          title: "chore: bump version to ${{ steps.update_manifest.outputs.version }}"
          body: "This PR bumps the version to ${{ steps.update_manifest.outputs.version }}"
          base: master
          labels: |
            version-bump

      - name: Auto-merge PR
        if: steps.create_pr.outputs.pull-request-url != ''
        run: gh pr merge ${{ steps.create_pr.outputs.pull-request-url }} --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
